name: docker-images-build

on:
  push:
    branches:
      - "*"
    # paths:
    #   - "images/**"
    #   - ".github/workflows/*"

  pull_request:
    branches:
      - "*"
    # paths:
    #   - "images/**"
    #   - ".github/workflows/*"

  workflow_dispatch: # allows you to trigger manually

jobs:
  build-images:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        image: ["hub"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Publish images to DockerHub Registry
        if: github.ref == 'refs/heads/master' #&& github.event_name == 'push'
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ncarxdev/${{ matrix.image }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: images/${{ matrix.image }}/Dockerfile
          tags: "latest"
          tag_names: true
