name: docker-images-build

on:
  push:
    branches:
      - "*"
    paths:
      - "images/**"
      - ".github/workflows/*"

  pull_request:
    branches:
      - "*"
    paths:
      - "images/**"
      - ".github/workflows/*"

  workflow_dispatch: # allows you to trigger manually

jobs:
  build-images:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        image: ["hub"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Build images
        run: |
          invoke images.build --name ${{ matrix.image }}

      - name: List images
        run: |
          docker ps -a
          docker images

      - name: Publish images to DockerHub Registry
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ncarxdev/${{ matrix.image }}:latest
