name: CI

on:
  push:
    branches:
      - "*"

  pull_request:
    branches:
      - "*"

  workflow_dispatch: # allows you to trigger manually

jobs:
  build-images:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        image: ["base"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Build images
        run: |
          invoke images.build --name ${{ matrix.image }}
